### ISSUE TITLE
AS3935 bus address

### ISSUE THREAD

**Issue by bucherrolf** [pcfens/RaspberryPi-AS3935#25]
I'm getting the bus address 0x1a and not the standard 0x03 if I do i2cdetect. Then the demo script is stopping with
IOError [Errno 121] Remote I/O error...
I'm running raspberry PI 3 and of course adjustet the Bus to 1.
Any hints to solve the problem?
![unbenannt](https://cloud.githubusercontent.com/assets/23026072/23091658/6b640f50-f5bb-11e6-980c-25e3eb84560f.PNG)

**Comment by pcfens** [comment]
Have you tried the sensor without other devices to make sure none of the other devices are interfering?

**Comment by bucherrolf** [comment]
No I did. I’m going to run as an individual device and will give you a feedback,

 

Regards

 

Rolf

 

 

Von: Phil Fenstermacher [mailto:notifications@github.com] 
Gesendet: Samstag, 18. Februar 2017 16:35
An: pcfens/RaspberryPi-AS3935 <RaspberryPi-AS3935@noreply.github.com>
Cc: bucherrolf <rolf.ch.bucher@quickline.ch>; Author <author@noreply.github.com>
Betreff: Re: [pcfens/RaspberryPi-AS3935] AS3935 bus address (#25)

 

Have you tried the sensor without other devices to make sure none of the other devices are interfering?

**Comment by bucherrolf** [comment]
That’s is. As an individual only device it works perfectly. Many thanks. I should figure out which one is interfering. Connecting just one by one.

I will find out….

 

Finally so simple….uff

 

Kind regards

 

Rolf

 

 

Von: Phil Fenstermacher [mailto:notifications@github.com] 
Gesendet: Samstag, 18. Februar 2017 16:35
An: pcfens/RaspberryPi-AS3935 <RaspberryPi-AS3935@noreply.github.com>
Cc: bucherrolf <rolf.ch.bucher@quickline.ch>; Author <author@noreply.github.com>
Betreff: Re: [pcfens/RaspberryPi-AS3935] AS3935 bus address (#25)

 

Have you tried the sensor without other devices to make sure none of the other devices are interfering?

**Comment by bucherrolf** [comment]
Problem solved. Thanks for assistance.
![unbenannt](https://cloud.githubusercontent.com/assets/23026072/23162113/ffe8bbee-f82c-11e6-9cf8-2225f397e84b.PNG)
